// ConfigSchema.cpp -- GENERATED SHAPE, HAND-TUNED RANGES. See ConfigSchema.hpp.
#include "ConfigSchema.hpp"

const ConfigField kConfigFields[] = {

    // ---- World ----
    // Drives gridWidth/Height/Depth together via applyWorldShape. The other two are not listed
    // because they are not independently settable -- the world is a cube.
    { "World", "sim.grid_size", "Grid size", FieldKind::UInt,
      offsetof(TuningParams, gridWidth), 8.0, 512.0,
      "Voxels along each edge. Changing this rebuilds the world and clears it." },
    { "World", "render.march_max_steps", "March max steps", FieldKind::UInt,
      offsetof(TuningParams, marchMaxSteps), 0.0, 2048.0,
      nullptr },
    { "World", "render.shadow_max_steps", "Shadow max steps", FieldKind::UInt,
      offsetof(TuningParams, shadowMaxSteps), 0.0, 1024.0,
      nullptr },
    { "World", "render.resolution_scale", "Resolution scale", FieldKind::Float,
      offsetof(TuningParams, renderScale), 0.25, 2.0,
      "Pixels rendered, as a fraction of the window. Halving it quarters the pixel count, which is "
      "most of the cost of a raymarcher. Web build only for now -- the desktop draws at the "
      "swapchain's size and would need rendering to an offscreen target to honour this." },

    // ---- Rain ----
    { "Rain", "rain.start_layers", "Start layers", FieldKind::UInt,
      offsetof(TuningParams, rainStartLayers), 0.0, 32.0,
      nullptr },
    { "Rain", "rain.drops_per_tick", "Drops per tick", FieldKind::UInt,
      offsetof(TuningParams, rainDropsPerTick), 0.0, 500.0,
      nullptr },
    { "Rain", "rain.overshoot", "Overshoot", FieldKind::Float,
      offsetof(TuningParams, rainOvershoot), 0.0, 2.0,
      nullptr },
    { "Rain", "rain.darken_delay", "Darken delay", FieldKind::Float,
      offsetof(TuningParams, rainDarkenDelay), 0.0, 60.0,
      nullptr },

    // ---- Clouds ----
    { "Clouds", "cloud.count", "Count", FieldKind::UInt,
      offsetof(TuningParams, cloudCount), 0.0, 64.0,
      "hard-capped at 64 by the shaders" },
    { "Clouds", "cloud.drift_speed", "Drift speed", FieldKind::Float,
      offsetof(TuningParams, cloudDriftSpeed), 0.0, 20.0,
      "world units per second" },
    { "Clouds", "cloud.edge_fade_dist", "Edge fade dist", FieldKind::Float,
      offsetof(TuningParams, cloudEdgeFadeDist), 0.0, 100.0,
      "How far in from the world's edges the cloud deck tapers off. Without it the deck ends in a "
      "straight vertical wall exactly on the boundary, because a column past the edge reads as "
      "empty -- correct, and it looks like the sky was cut with a knife." },
    { "Clouds", "cloud.charge_saturation", "Charge saturation", FieldKind::Float,
      offsetof(TuningParams, cloudChargeSaturation), 100.0, 200000.0,
      nullptr },
    { "Clouds", "cloud.charge_ease_rate", "Charge ease rate", FieldKind::Float,
      offsetof(TuningParams, cloudChargeEaseRate), 0.0, 1.0,
      "per dispatch, so it is framerate-dependent by design" },
    { "Clouds", "cloud.min_alpha", "Min alpha", FieldKind::Float,
      offsetof(TuningParams, cloudMinAlpha), 0.0, 1.0,
      "set to 0 for a completely clear sky until steam appears" },
    { "Clouds", "cloud.max_alpha", "Max alpha", FieldKind::Float,
      offsetof(TuningParams, cloudMaxAlpha), 0.0, 1.0,
      nullptr },
    { "Clouds", "cloud.voxel_size", "Voxel size", FieldKind::Float,
      offsetof(TuningParams, cloudVoxelSize), 1.0, 16.0,
      nullptr },
    { "Clouds", "cloud.edge_threshold_min", "Edge threshold min", FieldKind::Float,
      offsetof(TuningParams, cloudEdgeThresholdMin), 0.0, 1.0,
      nullptr },
    { "Clouds", "cloud.edge_threshold_max", "Edge threshold max", FieldKind::Float,
      offsetof(TuningParams, cloudEdgeThresholdMax), 0.0, 1.0,
      nullptr },
    { "Clouds", "cloud.max_steps", "Max steps", FieldKind::UInt,
      offsetof(TuningParams, maxCloudSteps), 1.0, 256.0,
      "Step budget for the cloud march. It has to exceed the cells a ray crosses inside the cloud "
      "band or cloud vanishes at a distance -- a distant ray is a shallow one, and a shallow ray "
      "skims the band for the whole width of the world. Measured worst case is 98 cells at a "
      "128-cube and 184 at a 256-cube, so raise this alongside sim.grid_size." },
    { "Clouds", "cloud.check_interval_ticks", "Storm check interval", FieldKind::UInt,
      offsetof(TuningParams, cloudCheckIntervalTicks), 1.0, 100000.0,
      "Dispatches between storm checks. On each multiple of this the simulation asks whether any "
      "cloud block moved on the previous dispatch; if none did, a rain event begins. Counted in "
      "dispatches rather than seconds, so the speed slider scales it -- the profiler's tick counter "
      "is the same clock." },
    { "Clouds", "cloud.rain_wait_max_ticks", "Rain wait max", FieldKind::UInt,
      offsetof(TuningParams, rainWaitMaxTicks), 1.0, 2047.0,
      "The upper end of how long a raincloud hangs at the ceiling before falling as water. Each "
      "block picks its own target between the minimum and this, so a storm falls as scattered drops "
      "over a long while rather than as one sheet. Capped at 2047 by the 11-bit counter in the "
      "cloud word." },
    { "Clouds", "cloud.rain_wait_min_ticks", "Rain wait min", FieldKind::UInt,
      offsetof(TuningParams, rainWaitMinTicks), 1.0, 2047.0,
      "The lower end of that wait. Raising it toward the maximum makes a storm arrive all at once; "
      "widening the gap spreads it out." },
    { "Clouds", "cloud.steam_condense_ticks", "Steam condense ticks", FieldKind::UInt,
      offsetof(TuningParams, steamCondenseTicks), 1.0, 255.0,
      "Dispatches a steam voxel may go without moving before it condenses where it stands. A "
      "failsafe: steam normally condenses on reaching the roof or on rising into settled cloud, but "
      "a cloud block can rise into a steam voxel's cell, and steam in that position is touching "
      "cloud without being under it. Rather than enumerate those cases, stalled steam condenses." },
    { "Clouds", "cloud.smooth_rate", "Surface smooth rate", FieldKind::Float,
      offsetof(TuningParams, cloudSmoothRate), 0.01, 1.0,
      "How fast the drawn cloud surface follows the block field, per dispatch. The field is never "
      "still -- blocks rise, rainclouds fall -- so a surface drawn straight from this dispatch's "
      "counts changes every dispatch and the deck boils. Easing it lets the shape drift instead. "
      "1.0 disables the smoothing." },
    { "Clouds", "cloud.column_full_count", "Column full count", FieldKind::Float,
      offsetof(TuningParams, cloudColumnFullCount), 1.0, 512.0,
      "How many cloud blocks stacked in one column read as a fully dense cloud. Lower makes thin "
      "cloud look solid sooner. This is what keeps cloud density from depending on world size." },
    { "Clouds", "cloud.thickness_per_block", "Thickness per block", FieldKind::Float,
      offsetof(TuningParams, cloudThicknessPerBlock), 0.1, 16.0,
      "World units of cloud drawn per cloud block in the column, measured upward from the top of "
      "the pile. Larger makes the same amount of cloud stand taller over the world." },
    { "Clouds", "cloud.clump_threshold", "Clump threshold", FieldKind::UInt,
      offsetof(TuningParams, cloudClumpThreshold), 0.0, 26.0,
      "How many of a cloud block's 26 neighbours must also be cloud before it stops trying to move. "
      "UNUSED. Cloud spreads like sand, with no cohesion rule -- cohesion made it stack into "
      "towers like dirt instead of spreading along the ceiling." },

    // ---- Physics ----
    { "Physics", "physics.sand_moisture_capacity", "Sand moisture capacity", FieldKind::UInt,
      offsetof(TuningParams, sandMoistureCapacity), 0.0, 255.0,
      nullptr },
    { "Physics", "physics.dirt_moisture_capacity", "Dirt moisture capacity", FieldKind::UInt,
      offsetof(TuningParams, dirtMoistureCapacity), 0.0, 255.0,
      nullptr },
    { "Physics", "physics.sand_water_absorb_unit", "Sand water absorb unit", FieldKind::UInt,
      offsetof(TuningParams, sandWaterAbsorbUnit), 0.0, 255.0,
      nullptr },
    { "Physics", "physics.sand_clump_threshold", "Sand clump threshold", FieldKind::UInt,
      offsetof(TuningParams, sandClumpThreshold), 0.0, 255.0,
      nullptr },
    { "Physics", "physics.dirt_clump_threshold", "Dirt clump threshold", FieldKind::UInt,
      offsetof(TuningParams, dirtClumpThreshold), 0.0, 255.0,
      nullptr },
    { "Physics", "physics.wake_sleep_threshold", "Wake sleep threshold", FieldKind::UInt,
      offsetof(TuningParams, wakeSleepThreshold), 0.0, 255.0,
      nullptr },
    { "Physics", "physics.empty_below_wake_count", "Empty below wake count", FieldKind::UInt,
      offsetof(TuningParams, emptyBelowWakeCount), 0.0, 26.0,
      nullptr },
    { "Physics", "physics.water_spread_radius", "Water spread radius", FieldKind::UInt,
      offsetof(TuningParams, waterSpreadRadius), 1.0, 512.0,
      nullptr },
    { "Physics", "physics.fire_lifetime", "Fire lifetime", FieldKind::UInt,
      offsetof(TuningParams, fireLifetime), 1.0, 255.0,
      nullptr },
    { "Physics", "physics.fire_dry_rate", "Fire dry rate", FieldKind::UInt,
      offsetof(TuningParams, fireDryRate), 0.0, 255.0,
      nullptr },
    { "Physics", "physics.grass_grow_chance", "Grass grow chance", FieldKind::Float,
      offsetof(TuningParams, grassGrowChance), 0.0, 1.0,
      nullptr },
    { "Physics", "physics.grass_submerged_decay_chance", "Grass submerged decay chance", FieldKind::Float,
      offsetof(TuningParams, grassSubmergedDecayChance), 0.0, 1.0,
      nullptr },
    { "Physics", "physics.fire_burn_grass_chance", "Fire burn grass chance", FieldKind::Float,
      offsetof(TuningParams, fireBurnGrassChance), 0.0, 1.0,
      nullptr },
    { "Physics", "physics.fire_spread_chance", "Fire spread chance", FieldKind::Float,
      offsetof(TuningParams, fireSpreadChance), 0.0, 1.0,
      nullptr },
    { "Physics", "physics.steam_scatter_chance", "Steam scatter chance", FieldKind::Float,
      offsetof(TuningParams, steamScatterChance), 0.0, 1.0,
      nullptr },

    // ---- Black hole ----
    { "Black hole", "blackhole.horizon", "Horizon", FieldKind::UInt,
      offsetof(TuningParams, blackHoleHorizon), 0.0, 32.0,
      "measured past the body's surface, not from its centre" },
    { "Black hole", "blackhole.radius", "Radius", FieldKind::UInt,
      offsetof(TuningParams, blackHoleRadius), 1.0, 128.0,
      nullptr },
    { "Black hole", "blackhole.orbit_speed", "Orbit speed", FieldKind::Float,
      offsetof(TuningParams, blackHoleOrbitSpeed), 0.0, 20.0,
      nullptr },
    { "Black hole", "blackhole.infall", "Infall", FieldKind::Float,
      offsetof(TuningParams, blackHoleInfall), 0.0, 1.0,
      nullptr },
    { "Black hole", "blackhole.plane_grip", "Plane grip", FieldKind::Float,
      offsetof(TuningParams, blackHolePlaneGrip), 0.0, 1.0,
      nullptr },
    { "Black hole", "blackhole.glow", "Glow", FieldKind::Float,
      offsetof(TuningParams, blackHoleGlow), 0.0, 4.0,
      nullptr },
    { "Black hole", "blackhole.orbit_planes", "Orbit planes", FieldKind::UInt,
      offsetof(TuningParams, blackHoleOrbitPlanes), 1.0, 32.0,
      "hard-capped at 32 by the shaders" },
    { "Black hole", "blackhole.growth_cost", "Growth cost", FieldKind::Float,
      offsetof(TuningParams, blackHoleGrowthCost), 1.0, 10.0,
      "keep above 1.0 -- see the cascade note above" },
    { "Black hole", "blackhole.max_level", "Max level", FieldKind::UInt,
      offsetof(TuningParams, blackHoleMaxLevel), 0.0, 16.0,
      "8 -> a 17-voxel-wide body at full size" },
    { "Black hole", "blackhole.starve_grace", "Starve grace", FieldKind::UInt,
      offsetof(TuningParams, blackHoleStarveGrace), 0.0, 2000.0,
      "dispatches with nothing captured before decay starts" },
    { "Black hole", "blackhole.decay_rate", "Decay rate", FieldKind::UInt,
      offsetof(TuningParams, blackHoleDecayRate), 1.0, 5000.0,
      "mass shed per dispatch once starving" },

    // ---- Water ----
    { "Water", "water.shadow_transmit", "Shadow transmit", FieldKind::Float,
      offsetof(TuningParams, waterShadowTransmit), 0.0, 1.0,
      nullptr },
    { "Water", "water.wave_strength", "Wave strength", FieldKind::Float,
      offsetof(TuningParams, waterWaveStrength), 0.0, 5.0,
      nullptr },
    { "Water", "water.wave_scale", "Wave scale", FieldKind::Float,
      offsetof(TuningParams, waterWaveScale), 0.0, 5.0,
      nullptr },
    { "Water", "water.wave_speed", "Wave speed", FieldKind::Float,
      offsetof(TuningParams, waterWaveSpeed), 0.0, 10.0,
      nullptr },

    // ---- Lava ----
    { "Lava", "lava.stage_size", "Stage size", FieldKind::UInt,
      offsetof(TuningParams, lavaStageSize), 1.0, 64.0,
      "coolness per stage; 4x this is the solidify threshold" },
    { "Lava", "lava.viscosity", "Viscosity", FieldKind::Float,
      offsetof(TuningParams, lavaViscosity), 0.0, 1.0,
      "chance per tick to attempt a move at all" },
    { "Lava", "lava.spread_radius", "Spread radius", FieldKind::UInt,
      offsetof(TuningParams, lavaSpreadRadius), 1.0, 64.0,
      "how far it will look sideways for somewhere to fall" },
    { "Lava", "lava.water_cool", "Water cool", FieldKind::UInt,
      offsetof(TuningParams, lavaWaterCool), 0.0, 255.0,
      "coolness gained per water voxel flashed to steam" },
    { "Lava", "lava.moisture_cool", "Moisture cool", FieldKind::UInt,
      offsetof(TuningParams, lavaMoistureCool), 0.0, 255.0,
      "coolness gained per unit of soil moisture boiled off" },
    { "Lava", "lava.rest_cool_chance", "Rest cool chance", FieldKind::Float,
      offsetof(TuningParams, lavaRestCoolChance), 0.0, 1.0,
      "chance per tick to cool while settled (rule 7's clock)" },
    { "Lava", "lava.consume_chance", "Consume chance", FieldKind::Float,
      offsetof(TuningParams, lavaConsumeChance), 0.0, 1.0,
      "chance per tick to eat a neighbour it has already dried out" },
    { "Lava", "lava.ignite_chance", "Ignite chance", FieldKind::Float,
      offsetof(TuningParams, lavaIgniteChance), 0.0, 1.0,
      "chance per tick to set adjacent grass alight" },
    { "Lava", "lava.dark_stone_dry_chance", "Dark stone dry chance", FieldKind::Float,
      offsetof(TuningParams, darkStoneDryChance), 0.0, 1.0,
      "chance per tick for dark stone to shed one unit of water" },
    { "Lava", "lava.churn_rate", "Churn rate", FieldKind::Float,
      offsetof(TuningParams, lavaChurnRate), 0.0, 4.0,
      "Cycles per second that a lava voxel walks between its own stage's colour and its two neighbours'." },

    // ---- Locusts ----
    { "Locusts", "locust.tick_dispatches", "Tick dispatches", FieldKind::UInt,
      offsetof(TuningParams, locustTickDispatches), 1.0, 255.0,
      "dispatches per locust tick (~5 ticks/sec at 60fps)" },
    { "Locusts", "locust.stage_size", "Stage size", FieldKind::UInt,
      offsetof(TuningParams, locustStageSize), 1.0, 51.0,
      "head count per visual stage; 5 stages, so 50 is the cap" },
    { "Locusts", "locust.spawn_size", "Spawn size", FieldKind::UInt,
      offsetof(TuningParams, locustSpawnSize), 1.0, 255.0,
      "head count a hand-placed swarm starts with" },
    { "Locusts", "locust.max_size", "Max size", FieldKind::UInt,
      offsetof(TuningParams, locustMaxSize), 1.0, 255.0,
      "hard cap; exceeding it buds off a child swarm" },
    { "Locusts", "locust.bud_size", "Bud size", FieldKind::UInt,
      offsetof(TuningParams, locustBudSize), 1.0, 255.0,
      "head count a budded child starts with" },
    { "Locusts", "locust.eat_gain", "Eat gain", FieldKind::UInt,
      offsetof(TuningParams, locustEatGain), 0.0, 255.0,
      "head count gained per grass block finished" },
    { "Locusts", "locust.eat_ticks_min", "Eat ticks min", FieldKind::UInt,
      offsetof(TuningParams, locustEatTicksMin), 1.0, 255.0,
      "ticks to eat one grass block at the cap" },
    { "Locusts", "locust.eat_ticks_max", "Eat ticks max", FieldKind::UInt,
      offsetof(TuningParams, locustEatTicksMax), 1.0, 255.0,
      "ticks to eat one grass block at one stage" },
    { "Locusts", "locust.run_length", "Run length", FieldKind::UInt,
      offsetof(TuningParams, locustRunLength), 1.0, 7.0,
      "steps committed to a heading before re-scanning for grass" },
    { "Locusts", "locust.climb_chance", "Climb chance", FieldKind::Float,
      offsetof(TuningParams, locustClimbChance), 0.0, 1.0,
      "when blocked, chance to climb rather than turn" },
    { "Locusts", "locust.density_min", "Density min", FieldKind::Float,
      offsetof(TuningParams, locustDensityMin), 0.0, 1.0,
      "sub-cube fill of the sparsest stage" },
    { "Locusts", "locust.density_max", "Density max", FieldKind::Float,
      offsetof(TuningParams, locustDensityMax), 0.0, 1.0,
      "sub-cube fill of the densest stage" },
    { "Locusts", "locust.subdivision", "Subdivision", FieldKind::UInt,
      offsetof(TuningParams, locustSubdivision), 1.0, 8.0,
      "sub-cubes per voxel edge; 4 means up to 64 per block" },
    { "Locusts", "locust.crawl_rate", "Crawl rate", FieldKind::Float,
      offsetof(TuningParams, locustCrawlRate), 0.0, 30.0,
      "swarm re-scatters this many times a second" },

    // ---- Trees ----
    { "Trees", "tree.bloom_chance", "Bloom chance", FieldKind::Float,
      offsetof(TuningParams, treeBloomChance), 0.0, 0.05,
      "1 in 1000 grass blocks sprouts a tree instead" },
    { "Trees", "tree.max_height", "Max height", FieldKind::UInt,
      offsetof(TuningParams, treeMaxHeight), 1.0, 64.0,
      "trunk voxels in a full-grown column" },
    { "Trees", "tree.soil_reserve", "Soil reserve", FieldKind::UInt,
      offsetof(TuningParams, treeSoilReserve), 0.0, 255.0,
      "soil moisture a trunk will not drink below" },
    { "Trees", "tree.water_max", "Water max", FieldKind::UInt,
      offsetof(TuningParams, treeWaterMax), 1.0, 255.0,
      "trunk water capacity (one byte, so this is the ceiling)" },
    { "Trees", "tree.drink_chance", "Drink chance", FieldKind::Float,
      offsetof(TuningParams, treeDrinkChance), 0.0, 1.0,
      "chance per tick to draw one unit out of the soil" },
    { "Trees", "tree.flow_chance", "Flow chance", FieldKind::Float,
      offsetof(TuningParams, treeFlowChance), 0.0, 1.0,
      "chance per tick to pass one unit up the trunk" },
    { "Trees", "tree.grow_cost", "Grow cost", FieldKind::UInt,
      offsetof(TuningParams, treeGrowCost), 1.0, 255.0,
      "water spent adding a trunk voxel" },
    { "Trees", "tree.leaf_cost", "Leaf cost", FieldKind::UInt,
      offsetof(TuningParams, treeLeafCost), 1.0, 255.0,
      "water spent putting out one leaf" },
    { "Trees", "tree.spread_cost", "Spread cost", FieldKind::UInt,
      offsetof(TuningParams, treeSpreadCost), 1.0, 255.0,
      "water spent seeding a neighbouring grass block" },
    { "Trees", "tree.spread_chance", "Spread chance", FieldKind::Float,
      offsetof(TuningParams, treeSpreadChance), 0.0, 1.0,
      "chance per tick to try, once the water is there" },
    { "Trees", "tree.leaf_chance", "Leaf chance", FieldKind::Float,
      offsetof(TuningParams, treeLeafChance), 0.0, 1.0,
      "chance per tick for a crown trunk to put out a leaf" },
    { "Trees", "tree.leaf_reach", "Leaf reach", FieldKind::UInt,
      offsetof(TuningParams, treeLeafReach), 1.0, 16.0,
      "how many leaves a canopy may chain from its crown" },
    { "Trees", "tree.leaf_spread_chance", "Leaf spread chance", FieldKind::Float,
      offsetof(TuningParams, treeLeafSpreadChance), 0.0, 1.0,
      "chance per leaf tick to extend the canopy" },
    { "Trees", "tree.leaf_tick_chance", "Leaf tick chance", FieldKind::Float,
      offsetof(TuningParams, treeLeafTickChance), 0.0, 1.0,
      "chance a leaf does anything at all this dispatch" },
    { "Trees", "tree.leaf_fall_chance", "Leaf fall chance", FieldKind::Float,
      offsetof(TuningParams, treeLeafFallChance), 0.0, 1.0,
      "chance per leaf tick for an unsupported leaf to let go" },
    { "Trees", "tree.trunk_burn_chance", "Trunk burn chance", FieldKind::Float,
      offsetof(TuningParams, treeTrunkBurnChance), 0.0, 1.0,
      "chance per tick for fire to take an adjacent trunk" },
    { "Trees", "tree.leaf_burn_chance", "Leaf burn chance", FieldKind::Float,
      offsetof(TuningParams, treeLeafBurnChance), 0.0, 1.0,
      "chance per tick for fire to take an adjacent leaf" },
    { "Trees", "tree.trunk_columns", "Trunk columns", FieldKind::UInt,
      offsetof(TuningParams, treeTrunkColumns), 1.0, 4.0,
      "upper bound on the little stems drawn inside a trunk" },
    { "Trees", "tree.trunk_radius", "Trunk radius", FieldKind::Float,
      offsetof(TuningParams, treeTrunkRadius), 0.02, 0.5,
      "stem radius in voxel units" },

    // ---- Resetting ----
    // Last on purpose. These are the parameters of the Clear Grid button's purge -- the giant black
    // hole that eats the world -- so they describe how the simulation ENDS rather than how any part
    // of it behaves, and they have no business sitting between the black hole and the water.
    { "Resetting", "purge.level", "Level", FieldKind::UInt,
      offsetof(TuningParams, purgeLevel), 1.0, 32.0,
      "body radius at full mass -- 10 is 21 voxels across" },
    { "Resetting", "purge.mass", "Mass", FieldKind::UInt,
      offsetof(TuningParams, purgeMass), 1.0, 100000.0,
      "starting mass, and the divisor the size ramp is measured against" },
    { "Resetting", "purge.starve_grace", "Starve grace", FieldKind::UInt,
      offsetof(TuningParams, purgeStarveGrace), 0.0, 2000.0,
      "dispatches with nothing left to catch before it starts shrinking" },
    { "Resetting", "purge.decay_rate", "Decay rate", FieldKind::UInt,
      offsetof(TuningParams, purgeDecayRate), 1.0, 5000.0,
      "mass shed per dispatch while shrinking; 10000/200 = ~0.8s" },
    { "Resetting", "purge.orbit_speed", "Orbit speed", FieldKind::Float,
      offsetof(TuningParams, purgeOrbitSpeed), 0.0, 20.0,
      nullptr },
    { "Resetting", "purge.infall", "Infall", FieldKind::Float,
      offsetof(TuningParams, purgeInfall), 0.0, 1.0,
      nullptr },
};

const size_t kConfigFieldCount = sizeof(kConfigFields) / sizeof(kConfigFields[0]);
